name: akita

services:
  redis:
    image: redis:7-alpine
    container_name: akita-redis
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - akita

networks:
  akita:
    name: akita
    driver: bridge

volumes:
  redis_data:
