server:
  port: 8080
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
      show-components: WHEN_AUTHORIZED
